export enum FitnessGoals {
  WeightLoss = 'Weight Loss',
  MuscleGain = 'Muscle Gain',
  Endurance = 'Endurance',
  Flexibility = 'Flexibility',
  GeneralHealth = 'General Health',
  StressRelief = 'Stress Relief',
  CardiovascularFitness = 'Cardiovascular Fitness',
  ImprovedEnergy = 'Improved Energy',
  BetterPosture = 'Better Posture',
  InjuryRecovery = 'Injury Recovery',
  SportSpecific = 'Sport Specific',
  BalanceAndCoordination = 'Balance and Coordination',
  ImprovedMobility = 'Improved Mobility',
  MentalWellness = 'Mental Wellness',
  CommunityEngagement = 'Community Engagement',
  WeightMaintenance = 'Weight Maintenance',
  BoneStrength = 'Bone Strength',
  LowerCholesterol = 'Lower Cholesterol',
  LowerBloodPressure = 'Lower Blood Pressure',
  DiabetesManagement = 'Diabetes Management',
}
